# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Disable AppArmor
        if: runner.os == 'Linux'
        run: |
          # Disable AppArmor for Ubuntu 23.10+.
          # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install WASM Browser Test
        run: go install github.com/agnivade/wasmbrowsertest@latest
      - name: Test
        env:
          GOOS: js
          GOARCH: wasm
        run: go test -exec wasmbrowsertest -v -race -timeout=5m ./browser
